apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      nodePort: 30432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: POSTGRES_DB
              value: budget
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-budget-pv-claim
          ports:
            - containerPort: 5432
      volumes:
        - name: postgres-budget-pv-claim
          persistentVolumeClaim:
            claimName: postgres-budget-pv-claim

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  password: dXBza2lsbC1idWRnZXQtYWd1c3RpbjNhOTQ=
type: Opaque
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-budget-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres-budget-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
